<?php

namespace AppBundle\Repository;

/**
 * guestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class guestbookRepository extends \Doctrine\ORM\EntityRepository
{
}
